version: '3.5'

services:
  mongo-express:
    image: mongo-express
    container_name: mexpress
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=topsecret
      - ME_CONFIG_MONGODB_URL=mongodb://root:topsecret@mongo:27017/?authSource=admin
      - ME_CONFIG_BASICAUTH_USERNAME=mexpress
      - ME_CONFIG_BASICAUTH_PASSWORD=mexpress
    links:
      - mongo
    restart: unless-stopped
    ports:
      - "8081:8081"
  mongo:
    container_name: marketplace-mongo
    image: mongo
    restart: on-failure
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: topsecret
    ports:
      - 27017:27017
    volumes:
      - ./docker/mongodb:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
#   redis:
#     container_name: marketplace-redis
#     image: 'redis:alpine'
#     ports:
#       - 6379:6379

#   rabbitmq:
#     image: rabbitmq:3-management-alpine
#     container_name: marketplace-rabbitmq
#     ports:
#       - 5672:5672
#       - 15672:15672
#     volumes:
#       - ~/.docker/rabbitmq/data/:/var/lib/rabbitmq/
#       - ~/.docker/rabbitmq/log/:/var/log/rabbitmq
#     networks:
#       - rabbitmq_net
# networks:
#   rabbitmq_net:
#     driver: bridge
